// <auto-generated />
namespace BorisHomeTask.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class User_WorkPlaces : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_WorkPlaces));
        
        string IMigrationMetadata.Id
        {
            get { return "201711182151055_User_WorkPlaces"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
